version: "4.8"

services:
  db:
    image: mysql:8.0
    container_name: empdb
    environment:
      MYSQL_ROOT_PASSWORD: Veeruved18
      MYSQL_DATABASE: empdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: emp_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/empdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Veeruved18
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build: ./frontend
    container_name: emp_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
