FROM openjdk:21

WORKDIR /app

COPY /target/Employee_Managment-0.0.1-SNAPSHOT.jar /app/Employee_Managment-0.0.1-SNAPSHOT.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "Employee_Managment-0.0.1-SNAPSHOT.jar"]
